// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuCOoUU9tjt7qEpk6Oxw62XB9EQKwMbVI',
    appId: '1:201343830980:web:8b9cfe3ab0d0a18b7e7291',
    messagingSenderId: '201343830980',
    projectId: 'finance-tracker-app-86606',
    authDomain: 'finance-tracker-app-86606.firebaseapp.com',
    storageBucket: 'finance-tracker-app-86606.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6u9zQbhmJQ2T7STt-FoXJEkspJ5E3Pfo',
    appId: '1:201343830980:android:4bd184ef18d3e5697e7291',
    messagingSenderId: '201343830980',
    projectId: 'finance-tracker-app-86606',
    storageBucket: 'finance-tracker-app-86606.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuCOoUU9tjt7qEpk6Oxw62XB9EQKwMbVI',
    appId: '1:201343830980:web:bc2699648ab64e547e7291',
    messagingSenderId: '201343830980',
    projectId: 'finance-tracker-app-86606',
    authDomain: 'finance-tracker-app-86606.firebaseapp.com',
    storageBucket: 'finance-tracker-app-86606.firebasestorage.app',
  );

}